version: '3.3'
services:
  web:
    build: .
    ports:
      - 8888:8888
    volumes:
      - "./src:/app/src"
      - "./.env:/app/.env"
      - "./dist:/app/dist"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always

volumes:
  mysql_db: